version: "3"
services:
    npm:
      container_name: orbis-training-project
      image: juansalvadorg/orbis-training-docker:1.0.0
      volumes:
        - ./:/app
      ports:
        - "3030:3030"
        - "35729:35729"
      command: npm start
      working_dir: /app
